// "use client"
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { SessionProvider } from "next-auth/react";

// import SessionWrapper from "@/components/SessionWrapper";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
      
//       <body className={`${inter.className}`}>
//       <SessionProvider>
//        <Navbar/>
//         {children}
//         <Footer/>
//         </SessionProvider>
//         </body>
        
//     </html>
//   );
// }


"use client"; // ✅ Zaroori hai kyunki SessionProvider ek client component hai

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

import { SessionProvider } from "next-auth/react";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navbar/>
          {children}
          <Footer/>
          </SessionProvider> {/* ✅ Wrap your app */}
      </body>
    </html>
  );
}
